### PR TITLE
Made form request mode configurable via configuration properties

### LINKED ISSUE #701: "Required request body is missing" when POSTing form
When POSTing to an endpoint with form content, "Required request body is missing" exception is thrown and a 400 error is returned.

## Expected Behavior
The request should be logged and a 200 returned

## Actual Behavior
An exception is thrown and a 400 is returned

## Possible Fix
It seems that setting the system property `logbook.servlet.form-request` to "PARAMETER" works around this issue, but an exception shouldn't be thrown with the default setup. Maybe calling getParameterMap before getInputStream in RemoteRequest would solve this.

It may also be better to read the `logbook.servlet.form-request` from application properties, similar to how `logbook.filter.enabled` is set.

## Steps to Reproduce
I've provided a minimal example to reproduce this issue at https://github.com/jbonzowh/logbook_bug

Run the project then run this curl command `curl http://localhost:8080/message -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'accountId=90240'`

## Your Environment
* Version used: logbook-spring-boot-starter 1.13.0, spring-boot 2.2.4.RELEASE, Java 8
* Link to your project: https://github.com/jbonzowh/logbook_bug

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #701

## Motivation and Context

Made form request mode configurable using configuration properties.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java [hunk 1]
```diff
@@ -17,9 +19,11 @@
 import java.util.UUID;
 
 import static javax.servlet.DispatcherType.ASYNC;
+import static lombok.AccessLevel.PRIVATE;
 import static org.apiguardian.api.API.Status.STABLE;
 
 @API(status = STABLE)
+@AllArgsConstructor(access = PRIVATE)
```
Comment (lukasniemeier-zalando) [inline logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java]: Intentionally hiding the constructor? Is there no use case for anyone programatically instantiating a `LogbookFilter` with a explicit `FormRequestMode`?

File: logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+ * Verifies that {@link LogbookFilter} delegates to {@link HttpLogWriter} correctly.
+ */
+final class FormRequestTest {
+
+    private final HttpLogFormatter formatter = spy(new ForwardingHttpLogFormatter(new DefaultHttpLogFormatter()));
+    private final HttpLogWriter writer = mock(HttpLogWriter.class);
+
+    @BeforeEach
+    void setUp() {
+        reset(formatter, writer);
```
Comment (lukasniemeier-zalando) [inline logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java]: Why is such `reset` required?

File: logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java (hunk 1 above)
Comment (whiskeysierra) [reply logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java]: I prefer to expose only the constructor with required arguments. So that a user get's the default by invoking the constructor but can subsequently override/configure things as needed using `with*` methods (convention over configuration).

File: logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java (hunk 2 above)
Comment (whiskeysierra) [reply logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java]: Nope, not needed. Probably a left over from an even earlier version of this test. Or just copy&pasted from somewhere else without giving it another though.

Comment (lukasniemeier-zalando) [reply logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java]: Ok thanks, I had a short panic attack that with JUnit 5 the test class life cycle has changed :-D

File: logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java (hunk 1 above)
Comment (lukasniemeier-zalando) [reply logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java]: Ah I've missed the `@With` annotation on the field, makes sense :+1:

**Comment by lukasniemeier-zalando** [comment]
:+1:
