### PR TITLE
Fixed missing content-type

### LINKED ISSUE #143: There is no Content-Type header in response with async requests
I have a spring controller that is defined like this:

@GetMapping(path = "somePath" produces = MediaType.APPLICATION_JSON_VALUE)
public ListenableFuture<SomeClass> retrieveSomething() {
    ...
}

Without logbook it returns the content type header, with logbook autoconfiguration the header is missing in response.

I haven't done any debuging on this issue. So i can not provide more details. Sorry.

### LINKED ISSUE #163: logbook messy code
I have upload the contain-bug project to my repository
https://github.com/wyzssw/logbookbug
please just execute LogbookbugApplication in IDE, and open browse http://localhost:8080/test

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #163
Fixes #143 

- [x] Same for request?
- [x] Make sure we're null safe there

### CODE REVIEW

File: logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java [hunk 1]
```diff
@@ -54,11 +54,6 @@ public String getProtocolVersion() {
     }
 
     @Override
-    public String getContentType() {
-        return Optional.ofNullable(super.getContentType()).orElse("");
```
Comment (AlexanderYastrebov) [inline logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java]: The fix is not obvious from the first sight, I suppose it changes `""` to `null`. Could you add a test maybe?

Comment (whiskeysierra) [inline logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java]: What it did before was to change `null` to `""`. The not obvious issue is/was that `LocalResponse` implements two different interfaces, `org.zalando.logbook.BaseHttpMessage` and `javax.servlet.http.HttpServletResponse`, and both share a common method `String getContentType()`. By converting `null` to `""` we accidentially changed the behaviour of the later one because from what I can tell the container (or the framework?) checks whether the content type was set by checking for `null`. 

I have no clue how to test this other than running the example provided by @wyzssw.

Comment (AlexanderYastrebov) [inline logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java]: At least we may assert that:
```diff
diff --git a/logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java b/logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java
index e0e7b39..43d684c 100644
--- a/logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java
+++ b/logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java
@@ -7,8 +7,11 @@ import javax.servlet.http.HttpServletResponse;
 import org.junit.Before;
 import org.junit.Test;
 
+import static org.hamcrest.Matchers.is;
+import static org.hamcrest.Matchers.nullValue;
 import static org.junit.Assert.assertNotSame;
 import static org.junit.Assert.assertSame;
+import static org.junit.Assert.assertThat;
 import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.times;
 import static org.mockito.Mockito.verify;
@@ -107,4 +110,10 @@ public class LocalResponseTest {
         unit.withBody();
     }
 
+    @Test
+    public void shouldReturnNullContentType() throws IOException {
+        when(mock.getContentType()).thenReturn(null);
+
+        assertThat(unit.getContentType(), is(nullValue()));
+    }
 }
```

Comment (AlexanderYastrebov) [inline logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java]: Ok, I have added an assertion test

**Comment by AlexanderYastrebov** [comment]
:+1:
