### PR TITLE
Fallback to simple String for invalid JSON body

### LINKED ISSUE #38: JsonHttpLogFormatter should be resilient against malformed JSON
Right now `JsonHttpLogFormatter#compactJson` tries to parse the request body based on the content-type. If you pass a malformed body (e.g. syntax error) an exception is thrown and the request will not be handled (and logged).

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
Fixes #38

### CODE REVIEW

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java [hunk 1]
```diff
@@ -101,10 +104,14 @@ private void addBody(final HttpMessage request, final ImmutableMap.Builder<Strin
         final String body = request.getBodyAsString();
 
         if (isJson(request.getContentType())) {
-            builder.put("body", body.isEmpty() ? JsonBody.EMPTY : new JsonBody(compactJson(body)));
-        } else {
-            addUnless(builder, "body", request.getBodyAsString(), String::isEmpty);
+            try {
+                builder.put("body", body.isEmpty() ? JsonBody.EMPTY : new JsonBody(compactJson(body)));
+                return;
```
Comment (jhorstmann) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: Control flow is a bit confusing. Can we maybe extract a method returning an optional or nullable `JsonBody`?

Comment (lukasniemeier-zalando) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: Yes - actually, why do we differ in behavior for empty JSON-body and empty non-JSON-body @whiskeysierra ?

Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: > Yes - actually, why do we differ in behavior for empty JSON-body and empty non-JSON-body @whiskeysierra ?

I think we can switch those conditions and 

1. check for empty body
2. check for content type json

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java [hunk 2]
```diff
@@ -101,10 +104,14 @@ private void addBody(final HttpMessage request, final ImmutableMap.Builder<Strin
...
+            } catch (final Exception e) {
```
Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: Can't we catch something more specific here? `JsonProcessingException` maybe?

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java (hunk 1 above)
Comment (lukasniemeier-zalando) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: I tried this but then some tests were failing (those that are checking that for JSON an empty body is serialized as an empty string and for all other content-type the body is omitted). I'd go with omitting the body for an empty body, regardless of the content-type.

Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: > I tried this but then some tests were failing (those that are checking that for JSON an empty body is serialized as an empty string and for all other content-type the body is omitted). I'd go with omitting the body for an empty body, regardless of the content-type.

I think I remember now. Depending on which RFC one tries to honor, a json body can be an empty *json* string, i.e. `""`, which would be different from an empty body.

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java (hunk 2 above)
Comment (lukasniemeier-zalando) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: We would still have the unlikely case of an `IOException`...

Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: > We would still have the unlikely case of an IOException...

Ok, so this then?

```java
} catch (JsonProcessingException | IOException e) {
```

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java (hunk 1 above)
Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: > Control flow is a bit confusing. Can we maybe extract a method returning an optional or nullable JsonBody?

Would it make sense to use some kind of SPI here to allow *embedding* bodies as json for different content types? Because with the current approach one always needs to change the `JsonHttpLogFormatter`.

**Comment by lukasniemeier-zalando** [comment]
As this is a kind-of breaking bug in this library, should we merge this? We could open an issue to implement the SPI later.

**Comment by whiskeysierra** [comment]
> As this is a kind-of breaking bug in this library, should we merge this? We could open an issue to implement the SPI later.

Agreed. I created #41
