### PR TITLE
Fixed invalid json in case of empty json body

### LINKED ISSUE #13: Support empty bodies for application/json messages
The `JsonHttpLogFormatter` silently assumes a non-empty body in case the content type is JSON. Not sure if an empty body is technically valid JSON (I think it's not), but we could juse fallback to `null` here in our logged json string.

### PR DESCRIPTION
**Pull request by whiskeysierra**
This fixes #13

### CODE REVIEW

File: logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ private void addBody(final HttpMessage request, final ImmutableMap.Builder<Strin
         final String body = request.getBodyAsString();
 
         if (isJson(request.getContentType())) {
-            builder.put("body", new JsonBody(compactJson(body)));
+            builder.put("body", body.isEmpty() ? JsonBody.NULL : new JsonBody(compactJson(body)));
```
Comment (jhorstmann) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: Should this be an empty string instead? Otherwise you can't distinguish between an empty body and a body containing the string "null".

Comment (whiskeysierra) [inline logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java]: True. I changed it to an empty string.
